### ISSUE TITLE
Disallow "<no value>" in rendered `initHelp`

### ISSUE THREAD

**Issue by majori** [futurice/jalapeno#146]
Throw an error if the rendered `initHelp` contains "\<no value\>", meaning that the template uses variables which are not defined. This is already done for the template files: https://github.com/futurice/jalapeno/blob/main/pkg/engine/engine.go#L43-L46

**Comment by rchojn** [comment]
@majori can I take this one?

**Comment by rchojn** [comment]
Can you assign it to me, please?
