### ISSUE TITLE
CLI command to check if recipe has new versions

### ISSUE THREAD

**Issue by majori** [futurice/jalapeno#16]

**Comment by ilkka** [comment]
One thing to consider here is how to best use the output in GH Actions etc. For example should there be some sort of `--format` parameter that could be used to set step outputs? See https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-declaring-outputs-for-composite-actions

**Comment by majori** [comment]
CLI command `check` implemented, but GH Action is still missing

**Comment by majori** [comment]
We should probably do Github App instead of Action to handle recipe update checking
