### ISSUE TITLE
Create Terraform state bootstrap recipe as one of first possible "killer" recipes

### ISSUE THREAD

**Issue by majori** [futurice/jalapeno#20]
1. `backend.tf` is already commented or renamed
2. `terraform init`
3. `terraform apply -target azurerm_storage_container.terraform_state`
4. restore `backend.tf`
5. Provide necessary credentials
6. `terraform init -migrate-state -backend-config="storage_account_key=..."`

`apply` only on CI

- ask what cloud
- ask what CI (future stuff or only support GH actions)
- can ask for secrets
  - put secrets in jalapenoignored, gitignored tfvars file
  - or put secrets in CI secrets already

write a taskfile to do steps 1-6

think about multiple taskfiles because other recipes could also write them

**Comment by ilkka** [comment]
Would be interested in working on this but can't remember how it was supposed to work and can't find a good example in repos accessible to me :D

**Comment by majori** [comment]
I recall that I wrote the procedure somewhere, but couldn't find it anywhere. I'll try to scribble something to the description.

**Comment by ilkka** [comment]
Let's still do the (non-conditional) GitHub actions setup and then call this done for now
