### ISSUE TITLE
Allow skip template rendering for specific files

### ISSUE THREAD

**Issue by ilkka** [futurice/jalapeno#39]
Especially some recipes with Taskfiles can be tedious to create since every variable needs to be escaped in when rendering the recipe, like `{{"{{.MY_TASK_VARIABLE}}"}}`. To mitigate this, recipe could have `skipRenderForFiles` property which defines files which can be moved to project without rendering.

Special file extension could be used

**Comment by ilkka** [comment]
Doing this by _only_ running templates that end in ".tmpl" through the templating, others get rendered as-is. Wondering if it's worth the trouble to rename the "templates" directory to "contents" or something?

**Comment by majori** [comment]
I had an idea that could this be configured with a flag, so by default it renders all files, but with property something like `explicitTemplates: true` it renders only `.tmpl` files

**Comment by ilkka** [comment]
Yeah, that sounds good. Another option could be a `templateGlob` that's just `**/*` by default, but could be narrowed to `**/*.tmpl`, but maybe it's unnecessarily generic.

**Comment by ilkka** [comment]
...except the `templateGlob` does not work because if it's a freeform glob, how do we remove the template file ext? So maybe either `templateExt`or `explicitTemplates` like you suggested.
